spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

server:
  port: 2800${SEQUENCE_NO}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: ${spring.application.name}-${spring.profiles.active}-${SEQUENCE_NO}

management:
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
  endpoints:
    web:
      exposure:
        include: "*"
